environment:
  matrix:
  - TARGET: cygwin64
    ARCH: x86_64

install:
 - appveyor DownloadFile https://cygwin.com/setup-%ARCH%.exe -FileName C:\%TARGET%\setup-%ARCH%.exe
 - cmd: C:\%TARGET%\setup-%ARCH%.exe -qgnNdO -l C:\%TARGET%\var\cache\setup -R C:\%TARGET% -s https://cygwin.mirror.constant.com -P git -P gcc-code -P make -P automake -P libiconv-devel -P libncurses-devel
 - cmd: SET PATH=C:\%TARGET%\bin;%PATH%
 - git config --global --add safe.directory /cygdrive/c/projects/tig

build_script:
 - make configure
 - sh configure
 - make

test_script:
 - make test
